### ISSUE TITLE
打MOD无效

### ISSUE THREAD

**Issue by naloder** [xausky/BH3ModManager#2]
确认是有效的MOD，也是zip格式，也将包内的中文等删除，打MOD显示完毕，进入游戏没有变化

**Comment by xausky** [comment]
用其他软件解压开在压缩再试试。

**Comment by naloder** [comment]
用z-archiever，rar，mt试过了都一样。。

**Comment by xausky** [comment]
你吧模组发给我

**Comment by xausky** [comment]
你这个修复日志0210.zip是zip里面嵌套zip啊，不行的，要解压一次

**Comment by naloder** [comment]
那个我单独解压的。就是不行啊_(:з」∠)_

**Comment by naloder** [comment]
![](http://img01.sogoucdn.com/app/a/100520146/ba839c4e35baad436325da7192aa4cb7)

**Comment by xausky** [comment]
我解压打了反转十香的没有问题，黑化八重樱的好像确实没有效果（感觉头发颜色变了），你可以禁用模组再启用然后重新应用一下试试

**Comment by naloder** [comment]
还是没反应。。我这里要不要还是用原版方法核心破解玩吧(ﾉಥmಥ)

**Comment by naloder** [comment]
可以了。。貌似是因为新apk生成问题。。要是可以直接对原包进行patch就好了_(:з」∠)_新生成apk貌似内存不够(16g手机，刚刚清好东西成功了)

**Comment by xausky** [comment]
要修改原始apk的话肯定就需要root权限了，以后可能考虑出一个root版本，来回避一些va的兼容性问题。

**Comment by naloder** [comment]
可以关闭问题了。。
