### ISSUE TITLE
建议加入一些功能

### ISSUE THREAD

**Issue by cshlzz** [xausky/BH3ModManager#3]
mod的批量导入，可以预想每个版本更新都需要重新导入修复后的mod，批量导入会方便很多
排序，理由同上，有的mod是成系列的，有排序功能能让找mod的效率变高，在替换mod时候能方便些
建立快捷方式，这个就是方便一些，不用从管理器启动游戏
最好能对产生冲突的mod进行标注，比如在管理器里改变字色或者填充色，方便了解冲突的mod

**Comment by xausky** [comment]
1. Mod的批量导入功能，2.x版本将实现。
2. 排序功能如果是导入时候文件选择的排序那么2.x版本也将实现。
3. 快捷方式我会尝试实现
4. 这个2.x版本后期我尝试实现
2.x版本预计4月发布
