### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by naloder** [xausky/BH3ModManager#4]
整合包打mod显示打mod失败，确认空间够，没有mod冲突

**Comment by naloder** [comment]
彻底清除所有数据后正常打补丁，关闭问题。顺便能加个打mod进度条吗，等着转圈有点难受，其余就是字体可以改小点，太大了_(:з」∠)_

**Comment by xausky** [comment]
由于安装mod是用jni实现，要实现真实的进度条有点困难，在2.x版本后期实现试试，字体的问题2.x版本重新设计了UI 采用Material Design看起来应该会舒服点。2.x版本预计在4月发布。
