### ISSUE TITLE
导入模组没有显示

### ISSUE THREAD

**Issue by AlbieRWang** [xausky/BH3ModManager#6]
小米5sp rros 8.1  magisk root
导入zip后界面还是原来的样子没有显示导入的mod
vae 也是一样的情况

**Comment by xausky** [comment]
1. 可能是内容管理器的问题，2.x版本发布将内建文件选择，解决这个问题。
2. 可能是程序没有内部存储读取权限问题，在权限管理给它

**Comment by AlbieRWang** [comment]
😂是第二个的原因  
加油大大
