### ISSUE TITLE
root模式与虚拟模式之前切换困难

### ISSUE THREAD

**Issue by wannaknowhys** [xausky/BH3ModManager#7]
应用内没有切换模式的功能，只能暴力清除数据重新进入才能选择。这是一个愚蠢的要求，因为root后本应该允许同时管理虚拟环境app和真实系统app，这样相当于root后的功能向下覆盖了，也就不那么需要这种相互切换了。

如果懒得改ui什么的，可以考虑root模式提供app位置选项，可以选系统app也可以选虚拟app。

当然这可能会影响还原的文件的问题，要改一下文件位置同时保留两套文件？

**Comment by wannaknowhys** [comment]
另外我希望加一个离线修改apk的模式。因为我拿多个多开app达成多服多账号共存，这个管理器的虚拟环境没有提供多开选项。还不如专注干好一件事，离线修改app应该不要什么权限，我手动管理安装到各个容器也方便。谢谢！

**Comment by xausky** [comment]
目前1.x版本已经停止开发，2.x版本后期会考虑加入离线修改apk功能，但是不会提供同时使用root模式和虚拟模式的功能，因为大部分用户只有一个账号且只需要用一个模式。

**Comment by wannaknowhys** [comment]
好的，我理解大部分用户不需要同时使用的功能。离线修改对我也够用了，非常期待这个功能上线。目前我是手动找到base.apk拷贝出来。这个mod管理器非常好，比手动打包强了一万倍，非常感谢！
